#! /bin/bash
# shellcheck disable=1117


sync_root="${HOME}/sync"
init_flag_file="/usr/local/vm-init.complete"

# Bail as early as possible if we've already run init.
[ -f "$init_flag_file" ] && exit 0




# Ensure we have sudo credentials handy.
sudo true


original_dir="$( pwd )"
cd ~ || exit


puts() { printf "%b\n" "$1"; }
divider() { printf "%${COLUMNS}s" | tr ' ' '-'; }
section() { printf "\n\n"; divider; printf "%s\n" "$1"; }




section "Installing packages ..."

	sudo snap install --classic aws-cli          2> /dev/null
	sudo snap install --classic google-cloud-sdk 2> /dev/null
	sudo snap install --classic heroku           2> /dev/null
	sudo snap install           jq               2> /dev/null
	sudo snap install           shellcheck       2> /dev/null
	sudo snap install           yq               2> /dev/null

	sudo apt-get -qq update
	sudo apt-get -qqy install apt-file   \
	                          byobu      \
	                          curl       \
	                          figlet     \
	                          gcc        \
	                          git        \
	                          make       \
	                          qrencode   \
	                          tree       \
	                          wget

	sudo apt-get -qqy install -f  # Resolve possible dependency issues.




section "Loading the apt-file database ..."

	# No need to wait on this, so we'll nohup it.
	sudo nohup apt-file update > /dev/null 2>&1 &




section "Configuring system behaviours ..."

	# Set timezone ...
	sudo timedatectl set-timezone "America/Chicago"

	# Set sudo password appearance ...
	puts "Defaults pwfeedback" | sudo tee -a /etc/sudoers > /dev/null

	# Increase inotify watch limit ...
	sudo su -c '/usr/bin/echo -e "\n\nfs.inotify.max_user_watches = 524288\n\n" >> /etc/sysctl.conf'




section "Prepping for Ruby / Rails work ..."

	sudo apt-get -qqy install libpq-dev  # We can't build the 'pg' gem without this.
	/snap/bin/heroku plugins:install heroku-accounts  # Simple juggling of Heroku credentials.




section "Cleaning apt caches ..."

	sudo apt-get -qy autoremove  # Note we're purposefully not fully quieting the autoremove.
	sudo apt-get -qqy autoclean




section "Setting up cross-instance config sync ..."

	mkdir -p "$sync_root"
	gsutil -m cp -P -r 'gs://vm-sync/*' "$sync_root" > /dev/null
	"${sync_root}/vm-sync" "$sync_root"




section "Finalizing setup ..."

	# We need a way to determine that init ran to completion ...
	echo "complete" | sudo tee "$init_flag_file" > /dev/null

	# Notify of init completion ...
	read -r -d '' notification <<-EOF
		Hostname: $( hostname )
		External: $( vm-ip )
		Disk Use: $( df -h / --output=pcent,size,avail                           \
		             | sed -r -e '1 d'                                           \
		                      -e 's| +|:|g'                                      \
		                      -e 's|^:?(.*):(.*):(.*)$|\1 of \2 (\3 Available)|' )

		Ready In: $( uptime --pretty | cut --bytes '4-' )
		SSH Link: ssh://nestor@$( vm-ip )/
	EOF
	notify gcp "VM Ready: $( hostname )" "$notification"




cd "$original_dir" || exit
